// src/views/Home.jsx
import "../App.css";
import naama from "../assets/naama_crop.png";

function Home() {
  return (
    <article>
      <div id="home">
        <img id="face" src={naama} alt="naama" />
        <h1>Topias Saari</h1>
        <p>
          Located in Tampere, Finland. I currently work as a frontend developer
          for Kela and during off-hours on various visual projects.
        </p>
      </div>
    </article>
  );
}

export default Home;

// src/views/Home.vue
<template>
  <article class="aboutContainer">
    <div class="aboutText">
      <img id="face" src="../assets/ts_2021.jpg" alt="naama" />
      <p>
        Located in Tampere, Finland. I currently work as a frontend developer
        for Kela and during off-hours on various visual projects.
        <br />
        <br />
        <a href="https://www.instagram.com/topias/">@topias</a> on instagram and
        <a href="https://github.com/topiassaari">topiassaari</a> on github.
      </p>
    </div>
  </article>
</template>

<style lang="scss" scoped>
  .aboutText {
    width: 300px;
  }
  #face {
    width: 300px;
    height: 300px;
    margin-bottom: 30px;
  }
</style>
