// src/views/Projects.vue
<template>
  <article class="links">
    <div>
      <h2>Projects</h2>
      <p>
        If you are here to possibly offer me a job, I suggest starting from
        <router-link class="naviItem" to="/projects/work">Work</router-link>
        and then making your way down the list. If you are a friend who just
        wants to know what I'm up to on my free time...start from the bottom and
        go up.
      </p>
      <ul>
        <li>
          <router-link class="naviItem" to="/projects/work">
            <h3>Work</h3>
          </router-link>
        </li>
        <li>
          <router-link class="naviItem" to="/projects/dev">
            <h3>Web development</h3>
          </router-link>
        </li>
        <li>
          <router-link class="naviItem" to="/projects/videos">
            <h3>Videos</h3>
          </router-link>
        </li>
        <li>
          <router-link class="naviItem" to="/projects/personal">
            <h3>Personal</h3>
          </router-link>
        </li>
      </ul>
    </div>
  </article>
</template>

<style lang="scss" scoped>
  .links {
    padding: 32px;
    max-width: 600px;
  }
  li {
    margin: 30px 0;
  }
</style>

// src/views/Projects.jsx
import { Link } from "react-router-dom";
import "../App.css";

function Projects() {
  return (
    <article>
      <div id="projects">
        <h2>Projects</h2>
        <p>
          Here you can find a short selection of different academic, personal
          and work projects. If you are here for recruiting purposes, I suggest
          starting from <Link to="/projects/work">Work</Link> and then making
          your way down the list. If you are a friend who just wants to know
          what I&apos;m up to on my free time...start from the bottom and go up.
        </p>
        <ul>
          <li>
            <Link to="/projects/work">Work</Link>
          </li>
          <li>
            <Link to="/projects/dev">Web development</Link>
          </li>
          <li>
            <Link to="/projects/videos">Videos</Link>
          </li>
          <li>
            <Link to="/projects/personal">Personal</Link>
          </li>
        </ul>
      </div>
    </article>
  );
}

export default Projects;
